### ISSUE TITLE
data array as raster

### ISSUE THREAD

**Issue by yaskshelat** [DHI-GRAS/l8_angles#1]
Hi
I got an array values inside 'data' variable, but how do I save that as a text file or csv file to view it as a raster? Is it something that this script does it or we have to write our own script? 
Any suggested ideas?

please see attached snapshot.
<img width="419" alt="l8angles_error" src="https://user-images.githubusercontent.com/36253068/37795035-a6cae336-2de9-11e8-9834-82dfd1fb4c4f.png">

regards
Yask

**Comment by j08lue** [comment]
@yaskshelat, please see the [usage](https://github.com/DHI-GRAS/l8-angles#usage) instructions in the README:

> The function returns a dictionary, mapping angle type (sun/sat_az/zn, where az and zn is azimuth and zenith) to lists of numpy 2D arrays. Each array in a list correspond to a single band. The lists are ordered with respect to the input bands.

So what you get from the `calculate_angles` is a dictionary of lists of numpy arrays - even when you just asked for one type (`angle_type='SOLAR'`) and a single band (`bands=[3]`). 

To write the data to a file, you need to take the key you want from the dictionary  (`data['sun_az']`) and the index of the band.

So your code will work if you extract the numpy array with `a = data['sun_az'][0]` and then feed that to `np.savetxt`.

**Comment by yaskshelat** [comment]
Thanks a lot, that worked, Now I exported it in txt format using numpy using following code (just so that it can be useful to others)
```
import numpy
a = data['sun_az'][0]
numpy.savetxt(r"C:\band3_1_2.txt",a,delimiter=",")
```

Is there a simple way to create raster out of this text file? It is because it creates a huge text file (~1 GB) and its difficult to create raster out of that.

regards
Yask

**Comment by j08lue** [comment]
> Is there a simple way to create raster out of this text file?

This is a bit beyond the scope of this issue. But just to point you in the right direction: You should look into [`rasterio`](https://rasterio.readthedocs.io/en/latest/) for creating a GeoTIFF file from the array. You will need information about the image transform and projection, though, which you can get from the Landsat 8 metadata.

Something along the following lines:

```python
import rasterio
a = ...
profile = dict(driver='GTiff', shape=a.shape, transform=..., crs={'init': 'epsg:...'}, count=1)
with rasterio.open('myfile.tif', 'w', **profile) as dst:
    dst.write_band(1, a)
```

Please open a question on StackOverflow if you need further help, as this is a rather general question regarding geospatial data in Python.
